apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
spec:
  type: LoadBalancer
  loadBalancerIP: "$LB_IP"
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PAPER"
            - name: MEMORY
              value: "6G"
            - name: ONLINE_MODE
              value: "FALSE"

            # Network / performance
            - name: NETWORK_COMPRESSION_THRESHOLD
              value: "64"
            - name: MAX_TICK_TIME
              value: "-1"
            - name: USE_AIKAR_FLAGS
              value: "true"

            # RCON (ใช้สำหรับ save-all flush ก่อน snapshot)
            - name: ENABLE_RCON
              value: "true"
            - name: RCON_PASSWORD
              value: "admin"
            - name: RCON_PORT
              value: "25575"

          resources:
            requests:
              memory: "7Gi"
              cpu: "2"
            limits:
              memory: "7Gi"
              cpu: "2"
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-pvc
